dist: trusty
sudo: required

language: php

php:
  - 7.0

addons:
  sonarqube:
    branches:
    - sonarqube
    
before_script:
  - cp .env.travis .env.testing
  - mysql -e 'create database group_up_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate --env=testing

script:
  - vendor/bin/phpunit
  - sonar-scanner