language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database group_up_api_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit