language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env.testing
  - mysql -e 'create database group_up_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit