language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - touch storage/app/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate --env=testing

script:
  - vendor/bin/phpunit