dist: trusty
sudo: required

language: php

php:
  - 7.0

addons:
  sonarqube:
  branches:
    - master
    - develop
    - sonarqube
    
before_script:
  - cp .env.travis .env
  - mysql -e 'create database group_up_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - sonar-scanner